services:
#database section
  movieticketbooking.database:
    image: postgres:17
#infrastructure section
  movieticketbooking.rabbitmq:
    image: rabbitmq:3-management-alpine

  movieticketbooking.pgadmin:
    image: dpage/pgadmin4:8.14.0

  movieticketbooking.portainer:
    image: portainer/portainer-ce

  movieticketbooking.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  movieticketbooking.kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
# api section
  movieticketbooking.webhost:
    image: ${DOCKER_REGISTRY-}movie-ticket-booking-webhost:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/MovieTicketBooking.WebHost/Dockerfile
#network section
networks:
  default:
    name: movieticketbooking
    driver: bridge
#vollumes section
volumes:
  movieticketbooking_postgres_data:
    name: movieticketbooking_postgres_data
  movieticketbooking_portainer_data:
    name: movieticketbooking_portainer_data
  movieticketbooking_elasticsearch_data:
    name: movieticketbooking_elasticsearch_data
  movieticketbooking_pgadmin_data:
    name: movieticketbooking_pgadmin_data
  movieticketbooking_redis_data:
    name: movieticketbooking_redis_data