# This is a generated file. Not intended for manual editing.
services:
  webhost:
    build:
      context: "D:\\Study\\MovieTicketBooking\\MovieTicketBooking"
      dockerfile: "src/MovieTicketBooking.WebHost/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "movie-ticket-booking-webhost:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57400"
    volumes:
    - "D:\\Study\\MovieTicketBooking\\MovieTicketBooking\\src\\MovieTicketBooking.WebHost:/app:rw"
    - "D:\\Study\\MovieTicketBooking\\MovieTicketBooking:/src:rw"
    - "C:\\Users\\Admin\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\Admin\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Admin\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.3\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Admin\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_1_11_10_22_57:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
